const POSITION_CONFIG = {
    "ST": [{ "attr": "Dứt điểm", "weight": 18.0 }, { "attr": "Chọn vị trí", "weight": 13.0 }, { "attr": "Giữ bóng", "weight": 10.0 }, { "attr": "Lực sút", "weight": 10.0 }, { "attr": "Đánh đầu", "weight": 10.0 }, { "attr": "Phản ứng", "weight": 8.0 }, { "attr": "Rê bóng", "weight": 7.0 }, { "attr": "Sức mạnh", "weight": 5.0 }, { "attr": "Tốc độ", "weight": 5.0 }, { "attr": "Chuyền ngắn", "weight": 5.0 }, { "attr": "Tăng tốc", "weight": 4.0 }, { "attr": "Sút xa", "weight": 3.0 }, { "attr": "Vô lê", "weight": 2.0 }],
    "LW/RW": [{ "attr": "Rê bóng", "weight": 16.0 }, { "attr": "Giữ bóng", "weight": 14.0 }, { "attr": "Dứt điểm", "weight": 10.0 }, { "attr": "Chọn vị trí", "weight": 9.0 }, { "attr": "Chuyền ngắn", "weight": 9.0 }, { "attr": "Tạt bóng", "weight": 9.0 }, { "attr": "Phản ứng", "weight": 7.0 }, { "attr": "Tăng tốc", "weight": 7.0 }, { "attr": "Tầm nhìn", "weight": 6.0 }, { "attr": "Tốc độ", "weight": 6.0 }, { "attr": "Sút xa", "weight": 4.0 }, { "attr": "Khéo léo", "weight": 3.0 }],
    "CF": [{ "attr": "Giữ bóng", "weight": 15.0 }, { "attr": "Rê bóng", "weight": 14.0 }, { "attr": "Chọn vị trí", "weight": 13.0 }, { "attr": "Dứt điểm", "weight": 11.0 }, { "attr": "Phản ứng", "weight": 9.0 }, { "attr": "Chuyền ngắn", "weight": 9.0 }, { "attr": "Tầm nhìn", "weight": 8.0 }, { "attr": "Lực sút", "weight": 5.0 }, { "attr": "Tốc độ", "weight": 5.0 }, { "attr": "Tăng tốc", "weight": 5.0 }, { "attr": "Sút xa", "weight": 4.0 }, { "attr": "Đánh đầu", "weight": 2.0 }],
    "GK": [{ "attr": "TM đổ người", "weight": 21.0 }, { "attr": "TM bắt bóng", "weight": 21.0 }, { "attr": "TM chọn vị trí", "weight": 21.0 }, { "attr": "TM phản xạ", "weight": 21.0 }, { "attr": "Phản ứng", "weight": 11.0 }, { "attr": "TM phát bóng", "weight": 5.0 }],
    "CDM": [{ "attr": "Chuyền ngắn", "weight": 14.0 }, { "attr": "Cắt bóng", "weight": 14.0 }, { "attr": "Lấy bóng", "weight": 12.0 }, { "attr": "Giữ bóng", "weight": 10.0 }, { "attr": "Chuyền dài", "weight": 10.0 }, { "attr": "Kèm người", "weight": 9.0 }, { "attr": "Phản ứng", "weight": 7.0 }, { "attr": "Thể lực", "weight": 6.0 }, { "attr": "Xoạc bóng", "weight": 5.0 }, { "attr": "Quyết đoán", "weight": 5.0 }, { "attr": "Tầm nhìn", "weight": 4.0 }, { "attr": "Sức mạnh", "weight": 4.0 }],
    "CM": [{ "attr": "Chuyền ngắn", "weight": 17.0 }, { "attr": "Giữ bóng", "weight": 14.0 }, { "attr": "Tầm nhìn", "weight": 13.0 }, { "attr": "Chuyền dài", "weight": 13.0 }, { "attr": "Phản ứng", "weight": 8.0 }, { "attr": "Rê bóng", "weight": 7.0 }, { "attr": "Chọn vị trí", "weight": 6.0 }, { "attr": "Thể lực", "weight": 6.0 }, { "attr": "Lấy bóng", "weight": 5.0 }, { "attr": "Cắt bóng", "weight": 5.0 }, { "attr": "Sút xa", "weight": 4.0 }, { "attr": "Dứt điểm", "weight": 2.0 }],
    "CAM": [{ "attr": "Chuyền ngắn", "weight": 16.0 }, { "attr": "Giữ bóng", "weight": 15.0 }, { "attr": "Tầm nhìn", "weight": 14.0 }, { "attr": "Rê bóng", "weight": 13.0 }, { "attr": "Chọn vị trí", "weight": 9.0 }, { "attr": "Phản ứng", "weight": 7.0 }, { "attr": "Dứt điểm", "weight": 7.0 }, { "attr": "Sút xa", "weight": 5.0 }, { "attr": "Tăng tốc", "weight": 4.0 }, { "attr": "Chuyền dài", "weight": 4.0 }, { "attr": "Tốc độ", "weight": 3.0 }, { "attr": "Khéo léo", "weight": 3.0 }],
    "LM/RM": [{ "attr": "Rê bóng", "weight": 15.0 }, { "attr": "Giữ bóng", "weight": 13.0 }, { "attr": "Chuyền ngắn", "weight": 11.0 }, { "attr": "Tạt bóng", "weight": 10.0 }, { "attr": "Chọn vị trí", "weight": 8.0 }, { "attr": "Phản ứng", "weight": 7.0 }, { "attr": "Tăng tốc", "weight": 7.0 }, { "attr": "Tầm nhìn", "weight": 7.0 }, { "attr": "Dứt điểm", "weight": 6.0 }, { "attr": "Tốc độ", "weight": 6.0 }, { "attr": "Thể lực", "weight": 5.0 }, { "attr": "Chuyền dài", "weight": 5.0 }],
    "CB": [{ "attr": "Kèm người", "weight": 17.0 }, { "attr": "Cắt bóng", "weight": 14.0 }, { "attr": "Lấy bóng", "weight": 13.0 }, { "attr": "Xoạc bóng", "weight": 10.0 }, { "attr": "Đánh đầu", "weight": 10.0 }, { "attr": "Sức mạnh", "weight": 10.0 }, { "attr": "Quyết đoán", "weight": 7.0 }, { "attr": "Phản ứng", "weight": 5.0 }, { "attr": "Chuyền ngắn", "weight": 5.0 }, { "attr": "Giữ bóng", "weight": 4.0 }, { "attr": "Nhảy", "weight": 3.0 }, { "attr": "Tốc độ", "weight": 2.0 }],
    "LB/RB": [{ "attr": "Xoạc bóng", "weight": 14.0 }, { "attr": "Cắt bóng", "weight": 12.0 }, { "attr": "Lấy bóng", "weight": 11.0 }, { "attr": "Tạt bóng", "weight": 9.0 }, { "attr": "Thể lực", "weight": 8.0 }, { "attr": "Phản ứng", "weight": 8.0 }, { "attr": "Kèm người", "weight": 8.0 }, { "attr": "Chuyền ngắn", "weight": 7.0 }, { "attr": "Giữ bóng", "weight": 7.0 }, { "attr": "Tốc độ", "weight": 7.0 }, { "attr": "Tăng tốc", "weight": 5.0 }, { "attr": "Đánh đầu", "weight": 4.0 }],
    "LWB/RWB": [{ "attr": "Cắt bóng", "weight": 12.0 }, { "attr": "Tạt bóng", "weight": 12.0 }, { "attr": "Xoạc bóng", "weight": 11.0 }, { "attr": "Chuyền ngắn", "weight": 10.0 }, { "attr": "Thể lực", "weight": 10.0 }, { "attr": "Lấy bóng", "weight": 8.0 }, { "attr": "Giữ bóng", "weight": 8.0 }, { "attr": "Phản ứng", "weight": 8.0 }, { "attr": "Kèm người", "weight": 7.0 }, { "attr": "Tốc độ", "weight": 6.0 }, { "attr": "Rê bóng", "weight": 4.0 }, { "attr": "Tăng tốc", "weight": 4.0 }]
};

const ATTRS = [
    "Tăng tốc", "Tốc độ", "Rê bóng", "Giữ bóng", "Chuyền ngắn", "Dứt điểm", "Lực sút", "Đánh đầu", "Sút xa",
    "Chọn vị trí", "Tầm nhìn", "Phản ứng", "Vô lê", "Penalty", "Tạt bóng", "Chuyền dài", "Đá phạt", "Sút xoáy",
    "Khéo léo", "Thăng bằng", "Kèm người", "Lấy bóng", "Cắt bóng", "Xoạc bóng", "Sức mạnh", "Thể lực", "Quyết đoán",
    "Nhảy", "Bình tĩnh", "TM đổ người", "TM bắt bóng", "TM phát bóng", "TM phản xạ", "TM chọn vị trí"
];
